In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Load & EDA

In [3]:
from pathlib import Path
file_path = Path.cwd().parent / 'Smart_Green_Infrastructure_Monitoring_Sensors_-_Historical.csv'
df = pd.read_csv(file_path)
df

/var/folders/_t/ms_9wggj1s1d3vr5j_zzp07c0000gn/T/ipykernel_16889/756490121.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,Measurement Title,Measurement Description,Measurement Type,Measurement Medium,Measurement Time,Measurement Value,Units,Units Abbreviation,Measurement Period Type,Data Stream ID,Resource ID,Measurement ID,Record ID,Latitude,Longitude,Location
0,UI Labs Bioswale NWS Quantitative Precipitatio...,NaN,TimeWindowBoundary,NaN,05/08/2017 04:00:00 AM,0.0,universal coordinated time,UTC,Instantaneous,33265,65142,2519080667999999999,332652519080667999999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
1,UI Labs Bioswale NWS Quantitative Precipitatio...,NaN,TimeWindowBoundary,NaN,05/07/2017 10:00:00 AM,0.0,universal coordinated time,UTC,Instantaneous,33265,65142,2519081315999999999,332652519081315999999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
2,UI Labs Bioswale NWS Quantitative Precipitatio...,NaN,TimeWindowBoundary,NaN,05/06/2017 10:00:00 AM,0.0,universal coordinated time,UTC,Instantaneous,33265,65142,2519082179999999999,332652519082179999999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
3,UI Labs Bioswale - Thunder 1: SM1 Soil Moistur...,SM1 Soil Moisture Sensor,SoilMoisture,Soil,05/08/2017 09:53:25 AM,951.0,millivolts,mV,Instantaneous,33303,65513,2519080455949999999,333032519080455949999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
4,UI Labs Bioswale - Thunder 1: SM1 Soil Moistur...,SM1 Soil Moisture Sensor,SoilMoisture,Soil,05/08/2017 09:52:23 AM,951.0,millivolts,mV,Instantaneous,33303,65513,2519080456569999999,333032519080456569999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13299694,Argyle - Cumulus: Weather Station Wind Speed,NaN,WindSpeed,NaN,03/10/2018 10:33:42 PM,0.0,meters per second,m/s,Instantaneous,40117,75340,2518815579770914463,401172518815579770914463,41.973086,-87.659725,POINT (-87.659725 41.973086)
13299695,Argyle - Cumulus: Weather Station Wind Speed,NaN,WindSpeed,NaN,03/10/2018 10:38:49 PM,0.0,meters per second,m/s,Instantaneous,40117,75340,2518815576709234016,401172518815576709234016,41.973086,-87.659725,POINT (-87.659725 41.973086)
13299696,Argyle - Cumulus: Weather Station Wind Speed,NaN,WindSpeed,NaN,03/10/2018 10:41:51 PM,0.0,meters per second,m/s,Instantaneous,40117,75340,2518815574881594255,401172518815574881594255,41.973086,-87.659725,POINT (-87.659725 41.973086)
13299697,Argyle - Cumulus: Weather Station Wind Speed,NaN,WindSpeed,NaN,03/10/2018 10:34:43 PM,0.0,meters per second,m/s,Instantaneous,40117,75340,2518815579161188365,401172518815579161188365,41.973086,-87.659725,POINT (-87.659725 41.973086)
13299698,Argyle - Cumulus: Weather Station Wind Speed,NaN,WindSpeed,NaN,03/10/2018 10:28:33 PM,0.0,meters per second,m/s,Instantaneous,40117,75340,2518815582861957602,401172518815582861957602,41.973086,-87.659725,POINT (-87.659725 41.973086)

In [4]:
df.isna().sum()

Measurement Title                0
Measurement Description    4114529
Measurement Type                 0
Measurement Medium         4114529
Measurement Time                 0
Measurement Value                0
Units                            0
Units Abbreviation               0
Measurement Period Type          0
Data Stream ID                   0
Resource ID                      0
Measurement ID                   0
Record ID                        0
Latitude                         0
Longitude                        0
Location                         0
dtype: int64

In [5]:
df = df.dropna()

In [6]:
len(df)

9185170

In [7]:
np.unique(df['Measurement Title'])

array(['Argyle - Thunder 1: MK-III Weather Station Pressure',
       'Argyle - Thunder 1: MK-III Weather Station RH',
       'Argyle - Thunder 1: MK-III Weather Station Rainfall',
       'Argyle - Thunder 1: MK-III Weather Station Temp',
       'Argyle - Thunder 1: MK-III Weather Station Wind Direction',
       'Argyle - Thunder 1: MK-III Weather Station Wind Speed',
       'Argyle - Thunder 1: SM1 Soil Moisture Sensor',
       'Argyle - Thunder 1: TM1 Temp Sensor',
       'Langley - Thunder 1: MK-III Weather Station Pressure',
       'Langley - Thunder 1: MK-III Weather Station RH',
       'Langley - Thunder 1: MK-III Weather Station Rainfall',
       'Langley - Thunder 1: MK-III Weather Station Temp',
       'Langley - Thunder 1: MK-III Weather Station Wind Direction',
       'Langley - Thunder 1: MK-III Weather Station Wind Speed',
       'Langley - Thunder 1: SM1 Soil Moisture Sensor',
       'Langley - Thunder 1: TM1 Temp Sensor',
       'UI Labs Bioswale - Thunder 1: MK-III Weather Station Pressure',
       'UI Labs Bioswale - Thunder 1: MK-III Weather Station RH',
       'UI Labs Bioswale - Thunder 1: MK-III Weather Station Rainfall',
       'UI Labs Bioswale - Thunder 1: MK-III Weather Station Temp',
       'UI Labs Bioswale - Thunder 1: MK-III Weather Station Wind Direction',
       'UI Labs Bioswale - Thunder 1: MK-III Weather Station Wind Speed',
       'UI Labs Bioswale - Thunder 1: SM1 Soil Moisture Sensor',
       'UI Labs Bioswale - Thunder 1: TM1 Temp Sensor'], dtype=object)

In [8]:
np.unique(df['Measurement Description'])

array(['MK-III Weather Station Pressure', 'MK-III Weather Station RH',
       'MK-III Weather Station Rainfall', 'MK-III Weather Station Temp',
       'MK-III Weather Station Wind Direction',
       'MK-III Weather Station Wind Speed', 'SM1 Soil Moisture Sensor',
       'TM1 Temp Sensor'], dtype=object)

In [9]:
np.unique(df['Measurement Type'])

array(['CumulativePrecipitation', 'DifferentialPressure',
       'RelativeHumidity', 'SoilMoisture', 'Temperature', 'WindDirection',
       'WindSpeed'], dtype=object)

In [10]:
np.unique(df['Measurement Medium'])

array(['Atmosphere', 'Soil'], dtype=object)

In [11]:
np.unique(df['Measurement Time'])

array(['01/01/2018 01:00:02 AM', '01/01/2018 01:00:02 PM',
       '01/01/2018 01:00:13 PM', ..., '12/31/2017 12:59:31 AM',
       '12/31/2017 12:59:34 PM', '12/31/2017 12:59:51 AM'], dtype=object)

In [12]:
df.columns

Index(['Measurement Title', 'Measurement Description', 'Measurement Type',
       'Measurement Medium', 'Measurement Time', 'Measurement Value', 'Units',
       'Units Abbreviation', 'Measurement Period Type', 'Data Stream ID',
       'Resource ID', 'Measurement ID', 'Record ID', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [13]:
np.unique(df['Measurement Value'])

array([ -550.,  -548.,  -547., ..., 65533., 65534., 65535.])

In [15]:
np.unique(df['Units'])

array(['count', 'degrees Celsius', 'degrees from north',
       'meters per second', 'millivolts', 'pascals', 'percent'],
      dtype=object)

In [16]:
np.unique(df['Units Abbreviation'])

array(['%', 'Pa', 'count', 'deg from north', 'degC', 'm/s', 'mV'],
      dtype=object)

In [17]:
np.unique(df['Measurement Period Type'])

array(['Cumulative', 'Instantaneous'], dtype=object)

In [18]:
np.unique(df['Data Stream ID'])

array([33303, 33305, 33307, 33309, 33311, 33313, 33315, 33317, 39174,
       39176, 39178, 39180, 39182, 39184, 39186, 39188, 39195, 39197,
       39199, 39201, 39203, 39205, 39207, 39209])

In [19]:
np.unique(df['Resource ID'])

array([65513, 65515, 65517, 65519, 65521, 65523, 65525, 65527, 73544,
       73546, 73548, 73550, 73552, 73554, 73556, 73558, 73565, 73567,
       73569, 73571, 73573, 73575, 73577, 73579])

In [20]:
np.unique(df['Measurement ID'])

array([2518776241079999999, 2518776241709999999, 2518776242349999999, ...,
       2519128808579999999, 2519128809079999999, 2519128809719999999])

In [21]:
np.unique(df['Record ID'])

array(['333032518776241079999999', '333032518776241709999999',
       '333032518776242349999999', ..., '392092519123447879999999',
       '392092519123448499999999', '392092519123449119999999'],
      dtype=object)

In [22]:
np.unique(df['Latitude'])

array([41.753112, 41.90715 , 41.973086])

In [23]:
np.unique(df['Longitude'])

array([-87.659725, -87.653996, -87.607731])

In [24]:
np.unique(df['Location'])

array(['POINT (-87.607731 41.753112)', 'POINT (-87.653996 41.90715)',
       'POINT (-87.659725 41.973086)'], dtype=object)

In [25]:
df

,Measurement Title,Measurement Description,Measurement Type,Measurement Medium,Measurement Time,Measurement Value,Units,Units Abbreviation,Measurement Period Type,Data Stream ID,Resource ID,Measurement ID,Record ID,Latitude,Longitude,Location
3,UI Labs Bioswale - Thunder 1: SM1 Soil Moistur...,SM1 Soil Moisture Sensor,SoilMoisture,Soil,05/08/2017 09:53:25 AM,951.0,millivolts,mV,Instantaneous,33303,65513,2519080455949999999,333032519080455949999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
4,UI Labs Bioswale - Thunder 1: SM1 Soil Moistur...,SM1 Soil Moisture Sensor,SoilMoisture,Soil,05/08/2017 09:52:23 AM,951.0,millivolts,mV,Instantaneous,33303,65513,2519080456569999999,333032519080456569999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
5,UI Labs Bioswale - Thunder 1: SM1 Soil Moistur...,SM1 Soil Moisture Sensor,SoilMoisture,Soil,05/08/2017 09:51:21 AM,951.0,millivolts,mV,Instantaneous,33303,65513,2519080457189999999,333032519080457189999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
6,UI Labs Bioswale - Thunder 1: SM1 Soil Moistur...,SM1 Soil Moisture Sensor,SoilMoisture,Soil,05/08/2017 09:50:19 AM,951.0,millivolts,mV,Instantaneous,33303,65513,2519080457809999999,333032519080457809999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
7,UI Labs Bioswale - Thunder 1: SM1 Soil Moistur...,SM1 Soil Moisture Sensor,SoilMoisture,Soil,05/08/2017 09:49:17 AM,951.0,millivolts,mV,Instantaneous,33303,65513,2519080458429999999,333032519080458429999999,41.907150,-87.653996,POINT (-87.653996 41.90715)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13299614,Langley - Thunder 1: TM1 Temp Sensor,TM1 Temp Sensor,Temperature,Atmosphere,03/10/2018 08:32:55 PM,403.0,millivolts,mV,Instantaneous,39197,73567,2518815652249999999,391972518815652249999999,41.753112,-87.607731,POINT (-87.607731 41.753112)
13299615,Langley - Thunder 1: TM1 Temp Sensor,TM1 Temp Sensor,Temperature,Atmosphere,03/10/2018 08:37:09 PM,429.0,millivolts,mV,Instantaneous,39197,73567,2518815649709999999,391972518815649709999999,41.753112,-87.607731,POINT (-87.607731 41.753112)
13299616,Langley - Thunder 1: TM1 Temp Sensor,TM1 Temp Sensor,Temperature,Atmosphere,03/10/2018 08:33:58 PM,401.0,millivolts,mV,Instantaneous,39197,73567,2518815651619999999,391972518815651619999999,41.753112,-87.607731,POINT (-87.607731 41.753112)
13299617,Langley - Thunder 1: TM1 Temp Sensor,TM1 Temp Sensor,Temperature,Atmosphere,03/10/2018 08:39:17 PM,501.0,millivolts,mV,Instantaneous,39197,73567,2518815648429999999,391972518815648429999999,41.753112,-87.607731,POINT (-87.607731 41.753112)
13299618,Langley - Thunder 1: TM1 Temp Sensor,TM1 Temp Sensor,Temperature,Atmosphere,03/10/2018 08:36:04 PM,430.0,millivolts,mV,Instantaneous,39197,73567,2518815650359999999,391972518815650359999999,41.753112,-87.607731,POINT (-87.607731 41.753112)

In [26]:
df.describe()

,Measurement Value,Data Stream ID,Resource ID,Measurement ID,Latitude,Longitude
count,9.185170e+06,9.185170e+06,9.185170e+06,9.185170e+06,9.185170e+06,9.185170e+06
mean,1.618808e+03,3.717984e+04,7.081217e+04,2.518971e+18,4.190200e+01,-8.764629e+01
std,3.305892e+03,2.787500e+03,3.811804e+03,9.679215e+13,8.435405e-02,2.067805e-02
min,-5.500000e+02,3.330300e+04,6.551300e+04,2.518776e+18,4.175311e+01,-8.765972e+01
25%,5.700000e+01,3.331300e+04,6.552300e+04,2.518893e+18,4.190715e+01,-8.765972e+01
50%,3.430000e+02,3.917800e+04,7.354800e+04,2.518976e+18,4.190715e+01,-8.765400e+01
75%,9.860000e+02,3.918800e+04,7.355800e+04,2.519059e+18,4.197309e+01,-8.765400e+01
max,6.553500e+04,3.920900e+04,7.357900e+04,2.519129e+18,4.197309e+01,-8.760773e+01

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9185170 entries, 3 to 13299618
Data columns (total 16 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Measurement Title        object
 1   Measurement Description  object
 2   Measurement Type         object
 3   Measurement Medium       object
 4   Measurement Time         object
 5   Measurement Value        float64
 6   Units                    object
 7   Units Abbreviation       object
 8   Measurement Period Type  object
 9   Data Stream ID           int64
 10  Resource ID              int64
 11  Measurement ID           int64
 12  Record ID                object
 13  Latitude                 float64
 14  Longitude                float64
 15  Location                 object
dtypes: float64(3), int64(3), object(10)
memory usage: 1.2+ GB

### Ideas 

- Would feature engineering be needed?
- What exactly am I trying to predict with the variables I'm given?
- Would I project where the green infrastructure is on a chicago map?
- What model would I train/use?

In [29]:
df.columns

Index(['Measurement Title', 'Measurement Description', 'Measurement Type',
       'Measurement Medium', 'Measurement Time', 'Measurement Value', 'Units',
       'Units Abbreviation', 'Measurement Period Type', 'Data Stream ID',
       'Resource ID', 'Measurement ID', 'Record ID', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')